apiVersion: v1
kind: Service
metadata:
  name: landev-service
  labels:
    app: landev
    version: v1.0
spec:
  type: NodePort
  selector:
    app: landev
    version: v1.0
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080


