name: "1. Security Checks"
on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Run Antivirus Scan
        uses: trufflesecurity/clamav-action@v1
        with:
          scan-dir: ./  
          fail-on-found: true 

      - name: Scan for secrets in code
        uses: gitleaks/gitleaks-action@v2
        with:
          config-path: .github/gitleaks.toml

      - name: Check for docker-compose.yml
        id: check_docker_compose
        run: |
          if [ -f "docker-compose.yml" ]; then
            echo "docker_compose_exists=true" >> $GITHUB_OUTPUT
          else
            echo "docker_compose_exists=false" >> $GITHUB_OUTPUT
          fi

      - name: Scan Docker for vulnerabilities
        if: steps.check_docker_compose.outputs.docker_compose_exists == 'true'
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          scan-ref: '.'

      - name: Add sec-passed label
        if: success()
        uses: actions-ecosystem/action-add-labels@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          labels: sec-passed
